services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: hydrateuser
      POSTGRES_PASSWORD: hydratepass
      POSTGRES_DB: hydrate_study
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
